@Library('yocto-lib@2.1') _

def machineFamilies = getFamilies('stm') + getFamilies('renesas')
def machineOptions = machineFamilies.collectMany { family -> getMachines(family) }
def imageOptions = getImages()

properties([
    parameters([
        [
            $class: 'ChoiceParameter',
            name: 'MACHINES',
            description: 'Select one or more machines. Or nothing for all.',
            choiceType: 'PT_CHECKBOX',
            filterable: true,
            script: [
                $class: 'GroovyScript',
                script: [
                    sandbox: true,
                    script: "return ${machineOptions.inspect()}"
                ]
            ]
        ],
        [
            $class: 'ChoiceParameter',
            name: 'IMAGES',
            description: 'Select one or more images. Or nothing for all.',
            choiceType: 'PT_CHECKBOX',
            filterable: true,
            script: [
                $class: 'GroovyScript',
                script: [
                    sandbox: true,
                    script: "return ${imageOptions.inspect()}"
                ]
            ]
        ],
        choice(
            name: 'MODE',
            choices: ['BUILD', 'BUILD + TEST', 'TEST'],
            description: 'Choose mode'
        ),
        booleanParam(
            name: 'BUILD_FEATURES',
            defaultValue: false,
            description: 'Build distro features'
        ),
        booleanParam(
            name: 'CREATE_RELEASE',
            defaultValue: false,
            description: 'Create and publish release'
        )
    ])
])

pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
        skipStagesAfterUnstable()
    }

    environment {
        GIT_URL = "${scm.userRemoteConfigs[0].url}"
        BRANCH_NAME =  "${env.TAG_NAME ? 'refs/tags/' + env.TAG_NAME : env.BRANCH_NAME}"
    }

    stages {
        stage('Validate Release') {
            when {
                expression { return params.CREATE_RELEASE }
            }

            steps {
                checkIfReleasable(params.MODE, env.GIT_URL, env.TAG_NAME)
            }
        }

        stage('Checkout') {      
            when {
                expression { return params.MODE.contains('BUILD') }
            }

            steps {
                deleteDir()

                checkoutYocto(
                    env.GIT_URL,
                    env.BRANCH_NAME
                )

                checkoutTestGrid('1.0')
            }
        }

        stage('Build Combinations') {
            matrix {
                axes {
                    axis {
                        name 'MACHINE'
                        values  'qsmp-1351', 
                                'qsmp-1530',
                                'qsmp-1570',
                                'qsmp-2030',
                                'qsmp-2350',
                                'qsmp-2550',
                                'txmp-1530',
                                'txmp-1570',
                                'txmp-1571',
                                'txmp-2550',
                                'txmp-2570',
                                'qsrz-g2l0',
                                'qsrz-g2l1',
                                'txrz-g2l0',
                                'txrz-g2l1',
                                'txrz-g2l2'
                    }
                }

                when {
                    expression {
                        def selected = (params.MACHINES ?: '')
                            .split(',')
                            .collect { it.trim() }
                            .findAll { it }

                        return selected.isEmpty() || selected.contains(env.MACHINE)
                    }
                }

                stages {
                    stage('Build') {
                        steps {
                            build job: "karo-bsp/yocto-build/2.1",
                                parameters: [
                                    string(name: 'WORKSPACE', value: env.WORKSPACE),
                                    string(name: 'MACHINE', value: env.MACHINE),
                                    string(name: 'IMAGES', value: env.IMAGES),
                                    string(name: 'MODE', value: params.MODE),
                                    booleanParam(name: 'BUILD_FEATURES', value: params.BUILD_FEATURES),
                                    booleanParam(name: 'SHARED_SSTATE', value: !params.CREATE_RELEASE)
                                ],
                                wait: true,
                                propagate: true
                        }
                    }
                }
            }
        }

        stage('Create Release') {
            when {
                expression { return params.CREATE_RELEASE }
            }

            stages {
                stage('Publish families') {
                    matrix {
                        axes {
                            axis {
                                name 'FAMILY'
                                values  'qsmp',
                                        'txmp',
                                        'qsrz',
                                        'txrz'
                            }
                        }

                        when {
                            expression {
                                def selected = (params.MACHINES ?: '')
                                    .split(',')
                                    .collect { it.trim() }
                                    .findAll { it }

                                return selected.isEmpty() || selected.containsAll(getMachines(env.FAMILY))
                            }
                        }

                        stages {
                            stage('Publish') {
                                steps {
                                    createRelease(env.FAMILY, env.TAG_NAME, env.IMAGES)
                                }
                            }
                        }
                    }
                }

                stage('Refresh sstate') {
                    steps {
                        refreshSstateMirror()
                    }
                }
            }

            post {
                always {
                    dir('sstate-cache') {
                        deleteDir()
                    }
                }
            }
        }
    }
}